# Generated by Django 2.2.2 on 2019-07-07 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=45)),
                ('status', models.CharField(blank=True, choices=[('created', 'Created'), ('paid', 'Paid')], max_length=20)),
                ('shipping_total', models.DecimalField(decimal_places=2, default=5.99, max_digits=25)),
                ('total', models.DecimalField(decimal_places=2, default=5.99, max_digits=25)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Cart')),
            ],
        ),
    ]
